<?php

namespace Mnu\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishRepository extends EntityRepository
{
}
