<?php

namespace Mnu\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Menu_dishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Menu_dishRepository extends EntityRepository
{
}
