mnu_bot:
    resource: "@MnuBotBundle/Resources/config/routing.yml"
    prefix:   /

mnu_main:
    resource: "@MnuMainBundle/Resources/config/routing.yml"
    prefix:   /

mnu_user:
    resource: "@MnuUserBundle/Resources/config/routing.yml"
    prefix:   /
