<?php

namespace Mnu\BotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotRestaurantRepository extends EntityRepository
{
    /**
     * Retourne un bot restaurant en fonction de son numéro
     * @param integer $number
     * @return \Mnu\BotBundle\Entity\BotRestaurant[]
     */
    public function findByNumber($number)
    {
        return $this->findBy(array('number' => $number));
    }
}
