<?php

namespace Mnu\BotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotRestaurantLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotRestaurantLinkRepository extends EntityRepository
{
}
