<?php

namespace Mnu\BotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotRestaurantRepository extends EntityRepository
{
}
